import { useState } from 'react'
import { Alert, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { useNavigation } from '@react-navigation/native'
import type { NativeStackNavigationProp } from '@react-navigation/native-stack'
import { useAuth } from '../auth/AuthContext'
import { useRemote } from '../hooks/useRemote'
import { colors, currency, shortDate } from '../theme'
import { modules, dateKey, type Row } from './domain'
import { Button, Empty, Icon, LoadState, Panel, Section, Tag, s } from './Ui'
import type { RootStack } from './navigation'
import { checkForAndroidUpdate } from '../updates'
const useNav = () => useNavigation<NativeStackNavigationProp<RootStack>>()
function Tile({ label, icon, onPress, color = colors.accent }: { label: string; icon: string; onPress: () => void; color?: string }) { return <Pressable accessibilityRole="button" onPress={onPress} style={[h.tile, { backgroundColor: `${color}08`, borderTopColor: color, borderTopWidth: 3 }]}><View style={[h.tileIcon, { backgroundColor: `${color}18` }]}><Icon name={icon} color={color} size={25} /></View><Text style={h.tileText}>{label}</Text></Pressable> }
export function HomeScreen() {
  const { user } = useAuth(), nav = useNav(), admin = user?.role === 'admin'
  const remote = useRemote<Row>(admin ? '/dashboard/kpi' : '/employees/summary'), data = remote.data
  const recent = useRemote<Row>(admin ? '/expenses?limit=4' : null)
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={remote.loading} onRefresh={() => { void remote.refresh(); void recent.refresh() }} />}>
    <View style={h.greeting}><View style={{ flex: 1 }}><Text style={h.eyebrow}>{new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short' })}</Text><Text style={h.greetingTitle}>Hello, {user?.name?.split(' ')[0] || 'there'}.</Text></View><Pressable accessibilityLabel="Your account" onPress={() => nav.navigate('Account')} style={h.avatar}><Text style={h.avatarText}>{(user?.name || user?.email || 'TX').slice(0, 2).toUpperCase()}</Text></Pressable></View>
    <LoadState loading={remote.loading && !data} error={remote.error} retry={remote.refresh} />
    {data && <View style={h.hero}>
      <Text style={h.heroLabel}>{admin ? 'AVAILABLE LEDGER BALANCE' : 'YOUR WORKSPACE'}</Text><Text style={h.heroValue}>{admin ? currency(data.availableBalance) : `${data.pendingLeave} pending leave`}</Text>
      <Text style={h.heroNote}>{admin ? 'Received deposits less recorded expenses' : 'Attendance, leave and payslips in one place'}</Text>
      <View style={h.heroDivider} /><View style={h.heroStats}><View style={{ flex: 1 }}><Text style={h.heroLabel}>{admin ? 'THIS MONTH SPENDING' : 'ATTENDANCE TODAY'}</Text><Text style={h.heroStat}>{admin ? currency(data.currentMonthSpend) : `${data.attendanceToday?.reduce((sum: number, item: Row) => sum + item.count, 0) || 0} entries`}</Text></View><View style={{ flex: 1 }}><Text style={h.heroLabel}>{admin ? 'YEAR TO DATE' : 'LEAVE STATUS'}</Text><Text style={h.heroStat}>{admin ? currency(data.currentYearSpend) : data.onLeaveCount ? 'On leave' : 'Working'}</Text></View></View>
    </View>}
    <Section title="Quick actions" />
    <View style={h.tiles}>{admin ? <><Tile label="Add expense" icon="add-circle-outline" color="#F04468" onPress={() => nav.navigate('Edit', { module: 'expenses' })} /><Tile label="Add deposit" icon="arrow-down-circle-outline" color={colors.success} onPress={() => nav.navigate('Edit', { module: 'deposits' })} /><Tile label="Analytics" icon="bar-chart-outline" color="#7A5AF8" onPress={() => nav.navigate('Analytics')} /><Tile label="Vyom" icon="sparkles-outline" color="#F79009" onPress={() => nav.navigate('AskAI')} /></> : <><Tile label="Attendance" icon="finger-print-outline" color="#06AED4" onPress={() => nav.navigate('Edit', { module: 'attendance' })} /><Tile label="Request leave" icon="leaf-outline" color={colors.success} onPress={() => nav.navigate('Edit', { module: 'leave' })} /><Tile label="Payslips" icon="document-text-outline" color="#7A5AF8" onPress={() => nav.navigate('Records', { module: 'payslips' })} /><Tile label="Leave balance" icon="pie-chart-outline" color="#F79009" onPress={() => nav.navigate('Records', { module: 'balances' })} /></>}</View>
    {admin && <><Section title="Recent expenses" action="See all" onPress={() => nav.navigate('Records', { module: 'expenses' })} /><LoadState loading={recent.loading && !recent.data} error={recent.error} retry={recent.refresh} />{recent.data?.expenses?.length ? <Panel>{recent.data.expenses.map((row: Row) => <Pressable key={row.id} accessibilityRole="button" onPress={() => nav.navigate('Detail', { module: 'expenses', row })} style={h.transaction}><View style={h.transactionIcon}><Icon name="receipt-outline" size={21} /></View><View style={{ flex: 1 }}><Text numberOfLines={1} style={h.rowTitle}>{row.description}</Text><Text style={s.caption}>{row.category?.name} · {shortDate(row.expenseDate)}</Text></View><Text style={h.transactionAmount}>{currency(row.baseCurrencyAmount)}</Text></Pressable>)}</Panel> : !recent.loading && !recent.error && <Empty title="No expenses yet" message="Add an expense to start your ledger." />}
      <Section title="Coming up" />{data?.upcomingExpenses?.length ? <Panel>{data.upcomingExpenses.slice(0, 4).map((row: Row) => <View key={row.id} style={h.transaction}><Icon name="time-outline" color={colors.amber} /><View style={{ flex: 1 }}><Text style={h.rowTitle}>{row.description}</Text><Text style={s.caption}>{shortDate(row.dueDate)}</Text></View><Text style={h.transactionAmount}>{currency(row.amount)}</Text></View>)}</Panel> : data && <Panel><Text style={s.caption}>No upcoming commitments in the next 30 days.</Text></Panel>}
    </>}
  </ScrollView>
}
export function GroupScreen({ group }: { group: 'finance' | 'people' }) {
  const nav = useNav(), { user } = useAuth(), admin = user?.role === 'admin'
  const rows = modules.filter(module => module.group === group && (!module.admin || admin))
  return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>{group === 'finance' ? 'Your finances' : 'People & work'}</Text><Text style={s.caption}>{group === 'finance' ? 'Record money in and out. Keep every detail in reach.' : 'Manage the workday, time off and payroll.'}</Text>
    {group === 'finance' && <View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button icon="add" label="Expense" onPress={() => nav.navigate('Edit', { module: 'expenses' })} /></View><View style={{ flex: 1 }}><Button secondary icon="add" label="Deposit" onPress={() => nav.navigate('Edit', { module: 'deposits' })} /></View></View>}
    {group === 'people' && <Button icon="finger-print-outline" label="Record attendance" onPress={() => nav.navigate('Edit', { module: 'attendance' })} />}
    {rows.map(module => <Pressable key={module.id} accessibilityRole="button" onPress={() => nav.navigate('Records', { module: module.id })} style={h.module}><View style={h.transactionIcon}><Icon name={module.icon} /></View><Text style={[h.rowTitle, { flex: 1 }]}>{module.title}</Text><Icon name="chevron-forward" color={colors.subtle} size={18} /></Pressable>)}
    {group === 'finance' && <Pressable accessibilityRole="button" onPress={() => nav.navigate('Analytics')} style={h.module}><View style={h.transactionIcon}><Icon name="bar-chart-outline" /></View><Text style={[h.rowTitle, { flex: 1 }]}>Spending analytics</Text><Icon name="chevron-forward" color={colors.subtle} size={18} /></Pressable>}
  </ScrollView>
}
export function ScheduleScreen() {
  const nav = useNav(), [offset, setOffset] = useState(0), [chosen, setChosen] = useState(dateKey())
  const date = new Date(`${chosen}T12:00:00`), params = new URLSearchParams({ startDate: chosen, endDate: chosen })
  const remote = useRemote<Row[]>(`/schedule/events?${params}`)
  const days = Array.from({ length: 7 }, (_, i) => { const value = new Date(); value.setDate(value.getDate() + offset * 7 + i); return value })
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={remote.loading} onRefresh={remote.refresh} />}>
    <View style={s.section}><Text style={s.title}>Your schedule</Text><Pressable accessibilityLabel="Add event" onPress={() => nav.navigate('Edit', { module: 'events' })} style={h.avatar}><Icon name="add" color="#fff" size={26} /></Pressable></View>
    <View style={s.section}><Pressable accessibilityLabel="Previous week" hitSlop={12} onPress={() => setOffset(value => value - 1)}><Icon name="chevron-back" /></Pressable><Text style={s.sectionTitle}>{days[0].toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</Text><Pressable accessibilityLabel="Next week" hitSlop={12} onPress={() => setOffset(value => value + 1)}><Icon name="chevron-forward" /></Pressable></View>
    <View style={{ flexDirection: 'row', gap: 5 }}>{days.map(value => <Pressable accessibilityRole="button" accessibilityLabel={value.toDateString()} key={dateKey(value)} onPress={() => setChosen(dateKey(value))} style={[h.day, chosen === dateKey(value) && { backgroundColor: colors.primary }]}><Text style={[h.dayLabel, chosen === dateKey(value) && { color: '#BDD4EF' }]}>{value.toLocaleDateString('en-IN', { weekday: 'short' }).slice(0, 2)}</Text><Text style={[h.dayNumber, chosen === dateKey(value) && { color: '#fff' }]}>{value.getDate()}</Text></Pressable>)}</View>
    <Section title={date.toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short' })} />
    <LoadState loading={remote.loading && !remote.data} error={remote.error} retry={remote.refresh} />
    {remote.data?.map(row => <Pressable key={row.id} accessibilityRole="button" onPress={() => nav.navigate('Detail', { module: 'events', row })} style={h.event}><View style={h.eventLine} /><View style={{ flex: 1, gap: 8 }}><Text style={s.link}>{row.isAllDay ? 'All day' : new Date(row.startsAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text><Text style={h.rowTitle}>{row.title}</Text><Text style={s.caption}>{row.location || row.ownerName || 'Scheduled event'}</Text><Tag value={row.priority} /></View></Pressable>)}
    {remote.data?.length === 0 && <Empty title="Your day is clear" message="Add an event or choose another day." icon="sunny-outline" />}
    <View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button secondary label="All events" onPress={() => nav.navigate('Records', { module: 'events' })} /></View><View style={{ flex: 1 }}><Button secondary label="Milestones" onPress={() => nav.navigate('Records', { module: 'milestones' })} /></View></View>
  </ScrollView>
}
export function MoreScreen() {
  const nav = useNav(), { user } = useAuth(), admin = user?.role === 'admin'
  const links: { title: string; icon: string; onPress: () => void }[] = [
    { title: 'Check for updates', icon: 'cloud-download-outline', onPress: () => void checkForAndroidUpdate().then(update => update ? Alert.alert(`Teinco-X ${update.version} is available`, update.notes || 'A newer version is ready.', [{ text: 'Later', style: 'cancel' }, { text: 'Download', onPress: () => void Linking.openURL(update.downloadUrl) }]) : Alert.alert('You are up to date', 'This is the latest Teinco-X version.')).catch(() => Alert.alert('Update check failed', 'Check your internet connection and try again.')) },
    { title: 'Subscriptions', icon: 'repeat-outline', onPress: () => nav.navigate('Records', { module: 'subscriptions' }) },
    ...(admin ? [{ title: 'Flow & intelligence', icon: 'sparkles-outline', onPress: () => nav.navigate('Flow') }, { title: 'Vyom', icon: 'chatbubble-ellipses-outline', onPress: () => nav.navigate('AskAI') }, { title: 'Settings', icon: 'settings-outline', onPress: () => nav.navigate('Settings') }] : []),
    { title: 'Account', icon: 'person-circle-outline', onPress: () => nav.navigate('Account') },
  ]
  return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>More from Teinco-X</Text><Text style={s.caption}>Your workspace tools and preferences.</Text>{links.map(link => <Pressable key={link.title} accessibilityRole="button" onPress={link.onPress} style={h.module}><View style={h.transactionIcon}><Icon name={link.icon} /></View><Text style={[h.rowTitle, { flex: 1 }]}>{link.title}</Text><Icon name="chevron-forward" size={18} color={colors.subtle} /></Pressable>)}<Text style={[s.caption, { textAlign: 'center', marginTop: 24 }]}>Teinco-X · Version 2.0.0</Text></ScrollView>
}
const h = StyleSheet.create({ greeting: { flexDirection: 'row', alignItems: 'center', gap: 14 }, eyebrow: { fontSize: 12, color: colors.muted, marginBottom: 6, fontWeight: '600' }, greetingTitle: { fontSize: 28, fontWeight: '800', color: colors.ink, letterSpacing: -.9 }, avatar: { width: 46, height: 46, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary, shadowColor: colors.primary, shadowOpacity: .22, shadowRadius: 9, elevation: 3 }, avatarText: { color: '#fff', fontWeight: '800' }, hero: { backgroundColor: colors.primary, borderRadius: 30, padding: 26, gap: 12, shadowColor: colors.primary, shadowOpacity: .24, shadowRadius: 18, shadowOffset: { width: 0, height: 9 }, elevation: 5 }, heroLabel: { fontSize: 9, fontWeight: '800', letterSpacing: 1, color: '#D9E1FF' }, heroValue: { fontSize: 35, fontWeight: '800', color: '#fff', letterSpacing: -1.2 }, heroNote: { fontSize: 11, lineHeight: 17, color: '#D9E1FF' }, heroDivider: { height: 1, backgroundColor: 'rgba(255,255,255,.22)', marginVertical: 5 }, heroStats: { flexDirection: 'row', gap: 18 }, heroStat: { fontSize: 18, fontWeight: '700', color: '#fff', marginTop: 7 }, tiles: { flexDirection: 'row', flexWrap: 'wrap', gap: 11 }, tile: { width: '47%', flexGrow: 1, backgroundColor: '#fff', padding: 19, borderRadius: 24, borderWidth: 1, borderColor: colors.border, gap: 13, shadowColor: '#315CF3', shadowOpacity: .06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, tileIcon: { width: 47, height: 47, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, tileText: { color: colors.ink, fontSize: 13, fontWeight: '700' }, transaction: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 10 }, transactionIcon: { width: 43, height: 43, borderRadius: 15, backgroundColor: colors.softBlue, alignItems: 'center', justifyContent: 'center' }, rowTitle: { color: colors.ink, fontSize: 15, fontWeight: '700' }, transactionAmount: { color: colors.ink, fontWeight: '700', fontSize: 13, maxWidth: '35%' }, module: { backgroundColor: '#fff', borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 19, flexDirection: 'row', alignItems: 'center', gap: 15, shadowColor: '#315CF3', shadowOpacity: .05, shadowRadius: 10, elevation: 1 }, day: { flex: 1, borderRadius: 17, backgroundColor: '#fff', alignItems: 'center', paddingVertical: 14, gap: 9, borderWidth: 1, borderColor: colors.border }, dayLabel: { fontSize: 11, color: colors.muted }, dayNumber: { fontSize: 18, fontWeight: '800', color: colors.ink }, event: { flexDirection: 'row', gap: 16, padding: 20, borderRadius: 22, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.border, shadowColor: '#315CF3', shadowOpacity: .05, shadowRadius: 10, elevation: 1 }, eventLine: { width: 4, backgroundColor: colors.accent, borderRadius: 4 } })
