import { useState } from 'react'
import { Pressable, RefreshControl, ScrollView, Text, View } from 'react-native'
import { useNavigation } from '@react-navigation/native'
import type { NativeStackNavigationProp } from '@react-navigation/native-stack'
import { useRemote } from '../hooks/useRemote'
import { themedStyles, colors, useMobileTheme } from '../theme'
import { dateKey, type Row } from './domain'
import { Button, Empty, Icon, LoadState, Section, Tag, s } from './Ui'
import type { RootStack } from './navigation'
const useNav = () => useNavigation<NativeStackNavigationProp<RootStack>>()
export function ScheduleScreen() {
  useMobileTheme()

  const nav = useNav(), [offset, setOffset] = useState(0), [chosen, setChosen] = useState(dateKey())
  const date = new Date(`${chosen}T12:00:00`), params = new URLSearchParams({ startDate: chosen, endDate: chosen })
  const remote = useRemote<Row[]>(`/schedule/events?${params}`)
  const days = Array.from({ length: 7 }, (_, i) => { const value = new Date(); value.setDate(value.getDate() + offset * 7 + i); return value })
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl tintColor={colors.primary} colors={[colors.primary]} progressBackgroundColor={colors.surface} refreshing={remote.loading} onRefresh={remote.refresh} />}>
    <View style={s.section}><Text style={s.title}>Your schedule</Text><Pressable accessibilityLabel="Add event" onPress={() => nav.navigate('Edit', { module: 'events' })} style={h.avatar}><Icon name="add" color={colors.onPrimary} size={26} /></Pressable></View>
    <View style={s.section}><Pressable accessibilityLabel="Previous week" style={{ minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center' }} onPress={() => setOffset(value => value - 1)}><Icon name="chevron-back" /></Pressable><Text style={s.sectionTitle}>{days[0].toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</Text><Pressable accessibilityLabel="Next week" style={{ minWidth: 48, minHeight: 48, alignItems: 'center', justifyContent: 'center' }} onPress={() => setOffset(value => value + 1)}><Icon name="chevron-forward" /></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{days.map(value => <Pressable accessibilityRole="button" accessibilityLabel={value.toDateString()} key={dateKey(value)} onPress={() => setChosen(dateKey(value))} style={[h.day, chosen === dateKey(value) && { backgroundColor: colors.primary }]}><Text style={[h.dayLabel, chosen === dateKey(value) && { color: colors.onPrimary }]}>{value.toLocaleDateString('en-IN', { weekday: 'short' }).slice(0, 2)}</Text><Text style={[h.dayNumber, chosen === dateKey(value) && { color: colors.onPrimary }]}>{value.getDate()}</Text></Pressable>)}</ScrollView>
    <Section title={date.toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short' })} />
    <LoadState loading={remote.loading && !remote.data} error={remote.error} retry={remote.refresh} />
    {remote.data?.map(row => <Pressable key={row.id} accessibilityRole="button" onPress={() => nav.navigate('Detail', { module: 'events', row })} style={h.event}><View style={h.eventLine} /><View style={{ flex: 1, gap: 8 }}><Text style={s.link}>{row.isAllDay ? 'All day' : new Date(row.startsAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text><Text style={h.rowTitle}>{row.title}</Text><Text style={s.caption}>{row.location || row.ownerName || 'Scheduled event'}</Text><Tag value={row.priority} /></View></Pressable>)}
    {remote.data?.length === 0 && <Empty title="Your day is clear" message="Add an event or choose another day." icon="sunny-outline" />}
    <View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button secondary label="All events" onPress={() => nav.navigate('Records', { module: 'events' })} /></View><View style={{ flex: 1 }}><Button secondary label="Milestones" onPress={() => nav.navigate('Records', { module: 'milestones' })} /></View></View>
  </ScrollView>
}
const h = themedStyles(() => ({ greeting: { flexDirection: 'row', alignItems: 'center', gap: 14 }, eyebrow: { fontSize: 12, color: colors.muted, marginBottom: 6, fontWeight: '600' }, greetingTitle: { fontSize: 28, fontWeight: '700', color: colors.ink, letterSpacing: -.9 }, avatar: { width: 48, height: 48, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary, shadowColor: colors.primary, shadowOpacity: .22, shadowRadius: 9, elevation: 3 }, avatarText: { color: colors.onPrimary, fontWeight: '700' }, hero: { backgroundColor: colors.hero, borderRadius: 20, padding: 26, gap: 12, shadowColor: colors.primary, shadowOpacity: .24, shadowRadius: 18, shadowOffset: { width: 0, height: 9 }, elevation: 5 }, heroLabel: { fontSize: 13, fontWeight: '700', letterSpacing: 1, color: colors.heroMuted }, heroValue: { fontSize: 35, fontWeight: '700', color: colors.heroText, letterSpacing: -1.2 }, heroNote: { fontSize: 13, lineHeight: 20, color: colors.heroMuted }, heroDivider: { height: 1, backgroundColor: 'rgba(255,255,255,.22)', marginVertical: 5 }, heroStats: { flexDirection: 'row', gap: 18 }, heroStat: { fontSize: 18, fontWeight: '700', color: colors.heroText, marginTop: 7 }, tiles: { flexDirection: 'row', flexWrap: 'wrap', gap: 11 }, tile: { width: '47%', flexGrow: 1, backgroundColor: colors.surface, padding: 19, borderRadius: 20, borderWidth: 1, borderColor: colors.border, gap: 13, shadowColor: colors.shadow, shadowOpacity: .06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, tileIcon: { width: 47, height: 47, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, tileText: { color: colors.ink, fontSize: 13, fontWeight: '700' }, transaction: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 10 }, transactionIcon: { width: 43, height: 43, borderRadius: 15, backgroundColor: colors.softBlue, alignItems: 'center', justifyContent: 'center' }, rowTitle: { color: colors.ink, fontSize: 15, fontWeight: '700' }, transactionAmount: { color: colors.ink, fontWeight: '700', fontSize: 13, maxWidth: '35%' }, module: { backgroundColor: colors.surface, borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 19, flexDirection: 'row', alignItems: 'center', gap: 15, shadowColor: colors.shadow, shadowOpacity: .05, shadowRadius: 10, elevation: 1 }, day: { minWidth: 48, paddingHorizontal: 8, borderRadius: 17, backgroundColor: colors.surface, alignItems: 'center', paddingVertical: 14, gap: 9, borderWidth: 1, borderColor: colors.border }, dayLabel: { fontSize: 11, color: colors.muted }, dayNumber: { fontSize: 18, fontWeight: '700', color: colors.ink }, event: { flexDirection: 'row', gap: 16, padding: 20, borderRadius: 22, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, shadowColor: colors.shadow, shadowOpacity: .05, shadowRadius: 10, elevation: 1 }, eventLine: { width: 4, backgroundColor: colors.accent, borderRadius: 4 } }))
