import { useState } from 'react'
import { Alert, Linking, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { useNavigation } from '@react-navigation/native'
import type { NativeStackNavigationProp } from '@react-navigation/native-stack'
import { useAuth } from '../auth/AuthContext'
import { request } from '../api'
import { useRemote } from '../hooks/useRemote'
import { themedStyles, colors, currency, shortDate, useMobileTheme } from '../theme'
import { modules, dateKey, type Row } from './domain'
import { Button, Empty, Icon, LoadState, Panel, Section, Tag, s } from './Ui'
import type { RootStack } from './navigation'
import { checkForAndroidUpdate } from '../updates'
const useNav = () => useNavigation<NativeStackNavigationProp<RootStack>>()
function Tile({ label, icon, onPress, color = colors.accent }: { label: string; icon: string; onPress: () => void; color?: string }) {
  useMobileTheme()
 return <Pressable accessibilityRole="button" onPress={onPress} style={[h.tile, { backgroundColor: colors.surface, borderColor: colors.border, borderTopColor: color, borderTopWidth: 3 }]}><View style={[h.tileIcon, { backgroundColor: `${color}18` }]}><Icon name={icon} color={color} size={25} /></View><Text style={[h.tileText, { color: colors.ink }]}>{label}</Text></Pressable> }
function EmployeeDashboard({ data, onOpen }: { data: Row; onOpen: (module: string) => void }) {
  const cards = [
    { label: 'Leave available', value: `${data.leaveBalance ?? 0} days`, icon: 'pie-chart-outline', color: colors.success, module: 'balances' },
    { label: 'Leave requests', value: `${data.pendingLeave ?? 0} pending`, icon: 'leaf-outline', color: colors.amber, module: 'leave' },
    { label: 'Payslips', value: String(data.payslipCount ?? 0), icon: 'document-text-outline', color: colors.violet, module: 'payslips' },
    { label: 'Vendors', value: String(data.vendorCount ?? 0), icon: 'storefront-outline', color: colors.cyan, module: 'vendors' },
  ]
  return <View style={{ gap: 12 }}><View style={{ backgroundColor: colors.hero, borderRadius: 30, padding: 24, gap: 10, shadowColor: colors.primary, shadowOpacity: .2, shadowRadius: 16, elevation: 4 }}><Text style={h.heroLabel}>YOUR WORKDAY</Text><Text style={{ fontSize: 30, fontWeight: '700', color: colors.heroText, letterSpacing: -.8 }}>{data.onLeaveCount ? 'On leave today' : 'Ready for today'}</Text><Text style={h.heroNote}>{data.leaveCycleLabel || 'Attendance, leave and payslips in one place'}</Text></View><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>{cards.map(card => <Pressable key={card.module} accessibilityRole="button" onPress={() => onOpen(card.module)} style={{ width: '47%', flexGrow: 1, borderRadius: 20, borderWidth: 1, padding: 15, gap: 7, backgroundColor: colors.surface, borderColor: colors.border }}><Icon name={card.icon} color={card.color} size={22} /><Text style={{ fontSize: 18, fontWeight: '700', color: colors.ink }}>{card.value}</Text><Text style={s.caption}>{card.label}</Text></Pressable>)}</View></View>
}
export function HomeScreen() {
  useMobileTheme()

  const { user } = useAuth(), nav = useNav(), admin = user?.role === 'admin'
  const remote = useRemote<Row>(admin ? '/dashboard/kpi' : '/employees/summary'), data = remote.data
  const recent = useRemote<Row>(admin ? '/expenses?limit=4' : null)
  const notifications = useRemote<Row[]>(admin ? '/employees/notifications' : null)
  const attendanceNotifications = notifications.data?.filter(item => item.type === 'attendance_checked_in' || item.type === 'attendance_checked_out').length || 0
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl tintColor={colors.primary} colors={[colors.primary]} progressBackgroundColor={colors.surface} refreshing={remote.loading} onRefresh={() => { void remote.refresh(); void recent.refresh() }} />}>
    <View style={h.greeting}><View style={{ flex: 1 }}><Text style={h.eyebrow}>{new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short' })}</Text><Text style={h.greetingTitle}>Hello, {user?.name?.split(' ')[0] || 'there'}.</Text></View>{admin && <Pressable accessibilityRole="button" accessibilityLabel={`${attendanceNotifications} attendance notifications`} onPress={() => nav.navigate('Records', { module: 'notifications' })} style={{ width: 46, height: 46, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, position: 'relative' }}><Icon name="notifications-outline" size={23} color={colors.ink} />{attendanceNotifications > 0 && <View style={{ position: 'absolute', top: -4, right: -4, minWidth: 19, height: 19, borderRadius: 10, paddingHorizontal: 4, backgroundColor: colors.danger, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: colors.onDanger, fontSize: 10, fontWeight: '700' }}>{attendanceNotifications > 9 ? '9+' : attendanceNotifications}</Text></View>}</Pressable>}<Pressable accessibilityLabel="Your account" onPress={() => nav.navigate('Account')} style={h.avatar}><Text style={h.avatarText}>{(user?.name || user?.email || 'TX').slice(0, 2).toUpperCase()}</Text></Pressable></View>
    <LoadState loading={remote.loading && !data} error={remote.error} retry={remote.refresh} />
    {data && !admin && <EmployeeDashboard data={data} onOpen={module => nav.navigate('Records', { module })} />}
    {data && admin && <View style={h.hero}>
      <Text style={h.heroLabel}>AVAILABLE LEDGER BALANCE</Text><Text style={h.heroValue}>{currency(data.availableBalance)}</Text>
      <Text style={h.heroNote}>Received deposits less recorded expenses</Text>
      <View style={h.heroDivider} /><View style={h.heroStats}><View style={{ flex: 1 }}><Text style={h.heroLabel}>THIS MONTH SPENDING</Text><Text style={h.heroStat}>{currency(data.currentMonthSpend)}</Text></View><View style={{ flex: 1 }}><Text style={h.heroLabel}>YEAR TO DATE</Text><Text style={h.heroStat}>{currency(data.currentYearSpend)}</Text></View></View>
    </View>}
    {!admin && <AttendanceClock />}
    <Section title="Quick actions" />
    <View style={h.tiles}>{admin ? <><Tile label="Add expense" icon="add-circle-outline" color={colors.danger} onPress={() => nav.navigate('Edit', { module: 'expenses' })} /><Tile label="Add deposit" icon="arrow-down-circle-outline" color={colors.success} onPress={() => nav.navigate('Edit', { module: 'deposits' })} /><Tile label="Analytics" icon="bar-chart-outline" color={colors.violet} onPress={() => nav.navigate('Analytics')} /><Tile label="Vyom" icon="sparkles-outline" color={colors.amber} onPress={() => nav.navigate('AskAI')} /></> : <><Tile label="Attendance history" icon="finger-print-outline" color={colors.cyan} onPress={() => nav.navigate('Records', { module: 'attendance' })} /><Tile label="Request leave" icon="leaf-outline" color={colors.success} onPress={() => nav.navigate('Edit', { module: 'leave' })} /><Tile label="Payslips" icon="document-text-outline" color={colors.violet} onPress={() => nav.navigate('Records', { module: 'payslips' })} /><Tile label="Vendors" icon="storefront-outline" color={colors.amber} onPress={() => nav.navigate('Records', { module: 'vendors' })} /></>}</View>
    {admin && <><Section title="Recent expenses" action="See all" onPress={() => nav.navigate('Records', { module: 'expenses' })} /><LoadState loading={recent.loading && !recent.data} error={recent.error} retry={recent.refresh} />{recent.data?.expenses?.length ? <Panel>{recent.data.expenses.map((row: Row) => <Pressable key={row.id} accessibilityRole="button" onPress={() => nav.navigate('Detail', { module: 'expenses', row })} style={h.transaction}><View style={h.transactionIcon}><Icon name="receipt-outline" size={21} /></View><View style={{ flex: 1 }}><Text numberOfLines={1} style={h.rowTitle}>{row.description}</Text><Text style={s.caption}>{row.category?.name} · {shortDate(row.expenseDate)}</Text></View><Text style={h.transactionAmount}>{currency(row.baseCurrencyAmount)}</Text></Pressable>)}</Panel> : !recent.loading && !recent.error && <Empty title="No expenses yet" message="Add an expense to start your ledger." />}
      <Section title="Coming up" />{data?.upcomingExpenses?.length ? <Panel>{data.upcomingExpenses.slice(0, 4).map((row: Row) => <View key={row.id} style={h.transaction}><Icon name="time-outline" color={colors.amber} /><View style={{ flex: 1 }}><Text style={h.rowTitle}>{row.description}</Text><Text style={s.caption}>{shortDate(row.dueDate)}</Text></View><Text style={h.transactionAmount}>{currency(row.amount)}</Text></View>)}</Panel> : data && <Panel><Text style={s.caption}>No upcoming commitments in the next 30 days.</Text></Panel>}
    </>}
  </ScrollView>
}
function AttendanceClock() {
  const { token, serverUrl } = useAuth(), attendance = useRemote<Row[]>(`/employees/attendance?date=${dateKey()}`)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), log = attendance.data?.[0]
  const checkedIn = Boolean(log?.checkIn), checkedOut = Boolean(log?.checkOut)
  const clock = async () => { if (busy || checkedOut) return; setBusy(true); setError(''); try { await request(serverUrl, '/employees/attendance/clock', token, { method: 'POST' }); await attendance.refresh() } catch (err) { setError(err instanceof Error ? err.message : 'Could not record attendance.') } finally { setBusy(false) } }
  const time = (value?: string) => value ? new Date(value).toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' }) : '—'
  return <Panel><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={h.transactionIcon}><Icon name="finger-print-outline" color={colors.cyan} /></View><View style={{ flex: 1 }}><Text style={s.sectionTitle}>Today’s attendance</Text><Text style={s.caption}>In {time(log?.checkIn)} · Out {time(log?.checkOut)}</Text></View></View><Button icon={checkedIn ? 'log-out-outline' : 'log-in-outline'} label={checkedOut ? 'Checked out' : checkedIn ? 'Check out now' : 'Check in now'} busy={busy} disabled={checkedOut || attendance.loading} onPress={() => void clock()} />{!!error && <Text accessibilityRole="alert" style={s.errorText}>{error}</Text>}</Panel>
}
export function GroupScreen({ group }: { group: 'finance' | 'people' }) {
  useMobileTheme()

  const nav = useNav(), { user } = useAuth(), admin = user?.role === 'admin'
  const rows = modules.filter(module => module.group === group && (!module.admin || admin))
  return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>{group === 'finance' ? 'Your finances' : 'People & work'}</Text><Text style={s.caption}>{group === 'finance' ? 'Record money in and out. Keep every detail in reach.' : 'Manage the workday, time off and payroll.'}</Text>
    {group === 'finance' && <View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button icon="add" label="Expense" onPress={() => nav.navigate('Edit', { module: 'expenses' })} /></View><View style={{ flex: 1 }}><Button secondary icon="add" label="Deposit" onPress={() => nav.navigate('Edit', { module: 'deposits' })} /></View></View>}
    {group === 'people' && <Button icon="finger-print-outline" label="Record attendance" onPress={() => nav.navigate('Edit', { module: 'attendance' })} />}
    {rows.map(module => <Pressable key={module.id} accessibilityRole="button" onPress={() => nav.navigate('Records', { module: module.id })} style={[h.module, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[h.transactionIcon, { backgroundColor: colors.softBlue }]}><Icon name={module.icon} /></View><Text style={[h.rowTitle, { flex: 1, color: colors.ink }]}>{module.title}</Text><Icon name="chevron-forward" color={colors.subtle} size={18} /></Pressable>)}
    {group === 'finance' && <Pressable accessibilityRole="button" onPress={() => nav.navigate('Analytics')} style={[h.module, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[h.transactionIcon, { backgroundColor: colors.softBlue }]}><Icon name="bar-chart-outline" /></View><Text style={[h.rowTitle, { flex: 1, color: colors.ink }]}>Spending analytics</Text><Icon name="chevron-forward" color={colors.subtle} size={18} /></Pressable>}
  </ScrollView>
}
export function ScheduleScreen() {
  useMobileTheme()

  const nav = useNav(), [offset, setOffset] = useState(0), [chosen, setChosen] = useState(dateKey())
  const date = new Date(`${chosen}T12:00:00`), params = new URLSearchParams({ startDate: chosen, endDate: chosen })
  const remote = useRemote<Row[]>(`/schedule/events?${params}`)
  const days = Array.from({ length: 7 }, (_, i) => { const value = new Date(); value.setDate(value.getDate() + offset * 7 + i); return value })
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl tintColor={colors.primary} colors={[colors.primary]} progressBackgroundColor={colors.surface} refreshing={remote.loading} onRefresh={remote.refresh} />}>
    <View style={s.section}><Text style={s.title}>Your schedule</Text><Pressable accessibilityLabel="Add event" onPress={() => nav.navigate('Edit', { module: 'events' })} style={h.avatar}><Icon name="add" color={colors.onPrimary} size={26} /></Pressable></View>
    <View style={s.section}><Pressable accessibilityLabel="Previous week" hitSlop={12} onPress={() => setOffset(value => value - 1)}><Icon name="chevron-back" /></Pressable><Text style={s.sectionTitle}>{days[0].toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</Text><Pressable accessibilityLabel="Next week" hitSlop={12} onPress={() => setOffset(value => value + 1)}><Icon name="chevron-forward" /></Pressable></View>
    <View style={{ flexDirection: 'row', gap: 5 }}>{days.map(value => <Pressable accessibilityRole="button" accessibilityLabel={value.toDateString()} key={dateKey(value)} onPress={() => setChosen(dateKey(value))} style={[h.day, chosen === dateKey(value) && { backgroundColor: colors.primary }]}><Text style={[h.dayLabel, chosen === dateKey(value) && { color: colors.onPrimary }]}>{value.toLocaleDateString('en-IN', { weekday: 'short' }).slice(0, 2)}</Text><Text style={[h.dayNumber, chosen === dateKey(value) && { color: colors.onPrimary }]}>{value.getDate()}</Text></Pressable>)}</View>
    <Section title={date.toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'short' })} />
    <LoadState loading={remote.loading && !remote.data} error={remote.error} retry={remote.refresh} />
    {remote.data?.map(row => <Pressable key={row.id} accessibilityRole="button" onPress={() => nav.navigate('Detail', { module: 'events', row })} style={h.event}><View style={h.eventLine} /><View style={{ flex: 1, gap: 8 }}><Text style={s.link}>{row.isAllDay ? 'All day' : new Date(row.startsAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text><Text style={h.rowTitle}>{row.title}</Text><Text style={s.caption}>{row.location || row.ownerName || 'Scheduled event'}</Text><Tag value={row.priority} /></View></Pressable>)}
    {remote.data?.length === 0 && <Empty title="Your day is clear" message="Add an event or choose another day." icon="sunny-outline" />}
    <View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button secondary label="All events" onPress={() => nav.navigate('Records', { module: 'events' })} /></View><View style={{ flex: 1 }}><Button secondary label="Milestones" onPress={() => nav.navigate('Records', { module: 'milestones' })} /></View></View>
  </ScrollView>
}
export function MoreScreen() {
  const nav = useNav(), { user } = useAuth(), admin = user?.role === 'admin'
  const { theme, toggle } = useMobileTheme()
  const links: { title: string; icon: string; onPress: () => void }[] = [
    { title: `${theme === 'dark' ? 'Dark' : 'Light'} theme`, icon: theme === 'dark' ? 'moon-outline' : 'sunny-outline', onPress: toggle },
    { title: 'Check for updates', icon: 'cloud-download-outline', onPress: () => void checkForAndroidUpdate().then(update => update ? Alert.alert(`Teinco-X ${update.version} is available`, update.notes || 'A newer version is ready.', [{ text: 'Later', style: 'cancel' }, { text: 'Download', onPress: () => void Linking.openURL(update.downloadUrl) }]) : Alert.alert('You are up to date', 'This is the latest Teinco-X version.')).catch(() => Alert.alert('Update check failed', 'Check your internet connection and try again.')) },
    { title: 'Subscriptions', icon: 'repeat-outline', onPress: () => nav.navigate('Records', { module: 'subscriptions' }) },
    ...(admin ? [{ title: 'Flow & intelligence', icon: 'sparkles-outline', onPress: () => nav.navigate('Flow') }, { title: 'Vyom', icon: 'chatbubble-ellipses-outline', onPress: () => nav.navigate('AskAI') }, { title: 'Settings', icon: 'settings-outline', onPress: () => nav.navigate('Settings') }] : []),
    { title: 'Account', icon: 'person-circle-outline', onPress: () => nav.navigate('Account') },
  ]
  return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>More from Teinco-X</Text><Text style={s.caption}>Your workspace tools and preferences.</Text>{links.map(link => <Pressable key={link.title} accessibilityRole="button" onPress={link.onPress} style={[h.module, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[h.transactionIcon, { backgroundColor: colors.softBlue }]}><Icon name={link.icon} /></View><Text style={[h.rowTitle, { flex: 1, color: colors.ink }]}>{link.title}</Text><Icon name="chevron-forward" size={18} color={colors.subtle} /></Pressable>)}<Text style={[s.caption, { textAlign: 'center', marginTop: 24 }]}>Teinco-X · Version 2.0.16</Text></ScrollView>
}
const h = themedStyles(() => ({ greeting: { flexDirection: 'row', alignItems: 'center', gap: 14 }, eyebrow: { fontSize: 12, color: colors.muted, marginBottom: 6, fontWeight: '600' }, greetingTitle: { fontSize: 28, fontWeight: '700', color: colors.ink, letterSpacing: -.9 }, avatar: { width: 46, height: 46, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary, shadowColor: colors.primary, shadowOpacity: .22, shadowRadius: 9, elevation: 3 }, avatarText: { color: colors.onPrimary, fontWeight: '700' }, hero: { backgroundColor: colors.hero, borderRadius: 30, padding: 26, gap: 12, shadowColor: colors.primary, shadowOpacity: .24, shadowRadius: 18, shadowOffset: { width: 0, height: 9 }, elevation: 5 }, heroLabel: { fontSize: 11, fontWeight: '700', letterSpacing: 1, color: colors.heroMuted }, heroValue: { fontSize: 35, fontWeight: '700', color: colors.heroText, letterSpacing: -1.2 }, heroNote: { fontSize: 11, lineHeight: 17, color: colors.heroMuted }, heroDivider: { height: 1, backgroundColor: 'rgba(255,255,255,.22)', marginVertical: 5 }, heroStats: { flexDirection: 'row', gap: 18 }, heroStat: { fontSize: 18, fontWeight: '700', color: colors.heroText, marginTop: 7 }, tiles: { flexDirection: 'row', flexWrap: 'wrap', gap: 11 }, tile: { width: '47%', flexGrow: 1, backgroundColor: colors.surface, padding: 19, borderRadius: 24, borderWidth: 1, borderColor: colors.border, gap: 13, shadowColor: colors.shadow, shadowOpacity: .06, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 2 }, tileIcon: { width: 47, height: 47, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, tileText: { color: colors.ink, fontSize: 13, fontWeight: '700' }, transaction: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 10 }, transactionIcon: { width: 43, height: 43, borderRadius: 15, backgroundColor: colors.softBlue, alignItems: 'center', justifyContent: 'center' }, rowTitle: { color: colors.ink, fontSize: 15, fontWeight: '700' }, transactionAmount: { color: colors.ink, fontWeight: '700', fontSize: 13, maxWidth: '35%' }, module: { backgroundColor: colors.surface, borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 19, flexDirection: 'row', alignItems: 'center', gap: 15, shadowColor: colors.shadow, shadowOpacity: .05, shadowRadius: 10, elevation: 1 }, day: { flex: 1, borderRadius: 17, backgroundColor: colors.surface, alignItems: 'center', paddingVertical: 14, gap: 9, borderWidth: 1, borderColor: colors.border }, dayLabel: { fontSize: 11, color: colors.muted }, dayNumber: { fontSize: 18, fontWeight: '700', color: colors.ink }, event: { flexDirection: 'row', gap: 16, padding: 20, borderRadius: 22, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, shadowColor: colors.shadow, shadowOpacity: .05, shadowRadius: 10, elevation: 1 }, eventLine: { width: 4, backgroundColor: colors.accent, borderRadius: 4 } }))
