import { ReactNode } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native'
import { Ionicons, type IoniconsIconName } from '@react-native-vector-icons/ionicons'
import { colors } from '../theme'
export function Icon({ name, size = 22, color = colors.primary }: { name: string; size?: number; color?: string }) { return <Ionicons name={name as IoniconsIconName} size={size} color={color} /> }
export function Button({ label, onPress, icon, busy, disabled, secondary, danger }: { label: string; onPress: () => void; icon?: string; busy?: boolean; disabled?: boolean; secondary?: boolean; danger?: boolean }) {
  const color = secondary ? colors.primary : '#fff'
  return <Pressable accessibilityRole="button" disabled={busy || disabled} onPress={onPress} style={({ pressed }) => [s.button, secondary && s.secondary, danger && { backgroundColor: colors.danger }, (pressed || busy || disabled) && { opacity: .55 }]}>{busy ? <ActivityIndicator color={color} /> : <>{icon && <Icon name={icon} color={color} size={20} />}<Text style={[s.buttonText, { color }]}>{label}</Text></>}</Pressable>
}
export function Search({ value, onChangeText, placeholder = 'Search records' }: { value: string; onChangeText: (v: string) => void; placeholder?: string }) { return <View style={s.search}><Icon name="search-outline" color={colors.muted} size={20} /><TextInput accessibilityLabel={placeholder} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={colors.muted} style={s.searchInput} autoCapitalize="none" />{!!value && <Pressable accessibilityLabel="Clear search" hitSlop={10} onPress={() => onChangeText('')}><Icon name="close-circle" color={colors.muted} size={20} /></Pressable>}</View> }
export function Chips({ items, value, onChange }: { items: { id: string; label: string }[]; value: string; onChange: (id: string) => void }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{items.map(item => <Pressable accessibilityRole="button" accessibilityState={{ selected: value === item.id }} key={item.id} onPress={() => onChange(item.id)} style={[s.chip, value === item.id && s.chipActive]}><Text style={[s.chipText, value === item.id && { color: '#fff' }]}>{item.label}</Text></Pressable>)}</ScrollView> }
export function Tag({ value }: { value?: string }) { if (!value) return null; const positive = ['active', 'approved', 'paid', 'present', 'complete', 'completed', 'resolved', 'received'].includes(value); return <View style={[s.tag, positive && { backgroundColor: colors.softGreen }]}><Text style={[s.tagText, positive && { color: colors.success }]}>{value.replace(/_/g, ' ')}</Text></View> }
export function Empty({ title = 'Nothing here yet', message = 'New records will appear here.', icon = 'file-tray-outline' }: { title?: string; message?: string; icon?: string }) { return <View style={s.empty}><View style={s.emptyIcon}><Icon name={icon} size={32} color={colors.muted} /></View><Text style={s.emptyTitle}>{title}</Text><Text style={s.emptyMessage}>{message}</Text></View> }
export function LoadState({ loading, error, retry }: { loading: boolean; error?: string | null; retry?: () => void }) { if (loading) return <View style={s.empty}><ActivityIndicator color={colors.accent} /><Text style={s.caption}>Loading your records…</Text></View>; if (!error) return null; return <View style={s.error}><Text accessibilityRole="alert" style={s.errorText}>{error}</Text>{retry && <Button secondary label="Try again" onPress={retry} />}</View> }
export function Section({ title, action, onPress }: { title: string; action?: string; onPress?: () => void }) { return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{action && <Pressable onPress={onPress} hitSlop={8}><Text style={s.link}>{action}</Text></Pressable>}</View> }
export function Panel({ children }: { children: ReactNode }) { return <View style={s.panel}>{children}</View> }
export function RowValue({ label, value }: { label: string; value?: unknown }) { if (value === undefined || value === null || value === '') return null; return <View style={s.valueRow}><Text style={s.valueLabel}>{label}</Text><Text selectable style={s.valueText}>{String(value)}</Text></View> }
export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background }, content: { padding: 20, paddingBottom: 36, gap: 16 }, title: { color: colors.ink, fontSize: 28, fontWeight: '800', letterSpacing: -.8 }, caption: { color: colors.muted, fontSize: 13, lineHeight: 20, marginTop: 4 },
  panel: { backgroundColor: colors.surface, borderRadius: 22, padding: 18, borderWidth: 1, borderColor: colors.border, gap: 10 },
  button: { minHeight: 50, borderRadius: 15, paddingHorizontal: 18, paddingVertical: 13, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, secondary: { backgroundColor: colors.softBlue }, buttonText: { fontSize: 14, fontWeight: '700' },
  search: { minHeight: 50, backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 9 }, searchInput: { flex: 1, color: colors.ink, fontSize: 14, paddingVertical: 13 },
  chips: { gap: 8, paddingVertical: 3 }, chip: { borderRadius: 24, paddingHorizontal: 16, paddingVertical: 11, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.border }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  tag: { borderRadius: 8, backgroundColor: '#FFF2DF', paddingHorizontal: 8, paddingVertical: 4, alignSelf: 'flex-start' }, tagText: { fontSize: 10, fontWeight: '700', color: colors.amber, textTransform: 'capitalize' },
  empty: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40, paddingHorizontal: 26, gap: 12 }, emptyIcon: { height: 68, width: 68, borderRadius: 24, backgroundColor: '#E8EEF5', alignItems: 'center', justifyContent: 'center' }, emptyTitle: { color: colors.ink, fontSize: 18, fontWeight: '700' }, emptyMessage: { color: colors.muted, textAlign: 'center', lineHeight: 20, fontSize: 13 },
  error: { padding: 18, borderRadius: 18, backgroundColor: '#FFF0F0', gap: 12 }, errorText: { color: colors.danger, fontSize: 14, lineHeight: 20 },
  section: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 4 }, sectionTitle: { fontWeight: '800', fontSize: 18, color: colors.ink, letterSpacing: -.3 }, link: { color: colors.accent, fontSize: 13, fontWeight: '700' },
  valueRow: { paddingVertical: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, gap: 5 }, valueLabel: { fontSize: 12, color: colors.muted }, valueText: { fontSize: 15, color: colors.ink, lineHeight: 22, fontWeight: '500' },
})
