import { ReactNode } from 'react'
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { colors } from '../theme'
export function Screen({ children, refreshing = false, onRefresh }: { children: ReactNode; refreshing?: boolean; onRefresh?: () => void }) { return <SafeAreaView edges={['left', 'right']} style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={onRefresh ? <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.primary} /> : undefined}>{children}</ScrollView></SafeAreaView> }
export function PageTitle({ title, subtitle }: { title: string; subtitle: string }) { return <View style={styles.heading}><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{subtitle}</Text></View> }
export function Card({ children }: { children: ReactNode }) { return <View style={styles.card}>{children}</View> }
export function State({ loading, error }: { loading: boolean; error?: string | null }) { if (loading) return <View style={styles.state}><ActivityIndicator color={colors.primary} /></View>; if (error) return <View style={styles.error}><Text style={styles.errorTitle}>Couldn’t load this view</Text><Text style={styles.errorText}>{error}</Text></View>; return null }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 36, gap: 14 }, heading: { marginBottom: 4 }, title: { fontSize: 27, lineHeight: 34, fontWeight: '800', color: colors.ink }, subtitle: { fontSize: 14, lineHeight: 20, color: colors.muted, marginTop: 3 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 16 }, state: { padding: 50, alignItems: 'center' }, error: { padding: 18, backgroundColor: '#FEF2F2', borderRadius: 14 }, errorTitle: { color: colors.danger, fontWeight: '700' }, errorText: { color: '#991B1B', marginTop: 4 } })
