import { Pressable, StyleSheet, Text, View } from 'react-native'
import { Card, PageTitle, Screen } from '../components/Ui'
import { useAuth } from '../auth/AuthContext'
import { colors } from '../theme'
export function AccountScreen() {
  const { user, serverUrl, logout } = useAuth(); const initials = (user?.name || user?.email || 'TX').split(/\s+/).map(v => v[0]).join('').slice(0, 2).toUpperCase()
  return <Screen><PageTitle title="Account" subtitle="Session and connection details." /><Card><View style={styles.profile}><View style={styles.avatar}><Text style={styles.initials}>{initials}</Text></View><View style={styles.flex}><Text style={styles.name}>{user?.name || 'Teinco-X user'}</Text><Text style={styles.email}>{user?.email}</Text><View style={styles.role}><Text style={styles.roleText}>{user?.role}</Text></View></View></View></Card><Card><Text style={styles.label}>CONNECTED BACKEND</Text><Text style={styles.server}>{serverUrl}</Text><Text style={styles.note}>The mobile app and web app use this same API and its Prisma/MySQL database.</Text></Card><Pressable onPress={() => void logout()} style={({ pressed }) => [styles.button, pressed && styles.pressed]}><Text style={styles.buttonText}>Sign out</Text></Pressable></Screen>
}
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center' }, avatar: { width: 56, height: 56, borderRadius: 18, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginRight: 14 }, initials: { color: '#fff', fontWeight: '900', fontSize: 18 }, flex: { flex: 1 }, name: { color: colors.ink, fontWeight: '800', fontSize: 17 }, email: { color: colors.muted, fontSize: 13, marginTop: 4 }, role: { alignSelf: 'flex-start', backgroundColor: colors.softBlue, borderRadius: 20, paddingHorizontal: 8, paddingVertical: 4, marginTop: 8 }, roleText: { color: colors.primary, fontWeight: '800', fontSize: 10, textTransform: 'uppercase' }, label: { color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: .6 }, server: { color: colors.ink, fontSize: 14, fontWeight: '700', marginTop: 9 }, note: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 8 }, button: { height: 50, borderRadius: 13, borderWidth: 1, borderColor: '#FCA5A5', backgroundColor: '#FEF2F2', justifyContent: 'center', alignItems: 'center' }, pressed: { opacity: .7 }, buttonText: { color: colors.danger, fontWeight: '800' } })
