import { useState } from 'react'
import { StyleSheet, Text, TextInput, View } from 'react-native'
import { Card, PageTitle, Screen, State } from '../components/Ui'
import { useRemote } from '../hooks/useRemote'
import { colors, currency, shortDate } from '../theme'
type Expense = { id: number; expenseId: string; description: string; expenseDate: string; baseCurrencyAmount: number; vendor?: { name: string }; category?: { name: string; color: string }; project?: { name: string } }
type ExpensePage = { expenses: Expense[]; total: number; page: number; totalPages: number }
export function ExpensesScreen() {
  const [query, setQuery] = useState(''); const path = `/expenses?limit=50${query.trim() ? `&search=${encodeURIComponent(query.trim())}` : ''}`; const remote = useRemote<ExpensePage>(path); const data = remote.data
  return <Screen refreshing={remote.loading} onRefresh={remote.refresh}><PageTitle title="Expenses" subtitle={data ? `${data.total} active transactions` : 'Search the shared company ledger.'} /><TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Search description or expense ID" clearButtonMode="while-editing" /><State loading={remote.loading && !data} error={remote.error} />{data?.expenses.map(item => <Card key={item.id}><View style={styles.top}><View style={styles.flex}><Text style={styles.title}>{item.description}</Text><Text style={styles.meta}>{item.expenseId} · {shortDate(item.expenseDate)}</Text></View><Text style={styles.amount}>{currency(item.baseCurrencyAmount)}</Text></View><View style={styles.tags}>{item.category && <View style={[styles.tag, { backgroundColor: `${item.category.color}18` }]}><Text style={[styles.tagText, { color: item.category.color }]}>{item.category.name}</Text></View>}{item.vendor && <Text style={styles.vendor}>{item.vendor.name}</Text>}</View></Card>)}{data && !data.expenses.length && <Card><Text style={styles.empty}>No expenses match this search.</Text></Card>}</Screen>
}
const styles = StyleSheet.create({ search: { height: 48, borderWidth: 1, borderColor: '#CBD5E1', backgroundColor: colors.surface, borderRadius: 13, paddingHorizontal: 14, color: colors.ink }, top: { flexDirection: 'row', gap: 12 }, flex: { flex: 1 }, title: { color: colors.ink, fontWeight: '700', fontSize: 15 }, meta: { color: colors.muted, fontSize: 12, marginTop: 6 }, amount: { color: colors.ink, fontWeight: '800', fontSize: 15 }, tags: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 13 }, tag: { borderRadius: 8, paddingVertical: 5, paddingHorizontal: 8 }, tagText: { fontSize: 11, fontWeight: '800' }, vendor: { color: colors.muted, fontSize: 12 }, empty: { color: colors.muted, textAlign: 'center' } })
