import { StyleSheet, Text, View } from 'react-native'
import { useAuth } from '../auth/AuthContext'
import { Card, PageTitle, Screen, State } from '../components/Ui'
import { useRemote } from '../hooks/useRemote'
import { colors, currency, shortDate } from '../theme'
type Kpi = { currentMonthSpend: number; currentYearSpend: number; monthlyAverage: number; recurringMonthlyCommitment: number; totalExpenses: number; categoryBreakdown: { category: string; amount: number; color: string }[]; upcomingExpenses: { id: number; description: string; vendor?: string; amount: number; dueDate?: string }[] }
type PeopleSummary = { headcount: number; pendingLeave: number; onLeaveCount: number; attendanceToday: { status: string; count: number }[]; privacy: { compensationAccess: string } }
function Metric({ label, value, note }: { label: string; value: string; note?: string }) { return <Card><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text>{note && <Text style={styles.note}>{note}</Text>}</Card> }
function AdminHome() {
  const remote = useRemote<Kpi>('/dashboard/kpi'); const data = remote.data
  return <Screen refreshing={remote.loading} onRefresh={remote.refresh}><PageTitle title="Financial overview" subtitle="Live numbers from the shared finance database." /><State loading={remote.loading && !data} error={remote.error} />{data && <>
    <View style={styles.metricGrid}><View style={styles.half}><Metric label="THIS MONTH" value={currency(data.currentMonthSpend)} /></View><View style={styles.half}><Metric label="YTD SPEND" value={currency(data.currentYearSpend)} note={`${data.totalExpenses} transactions`} /></View></View>
    <View style={styles.metricGrid}><View style={styles.half}><Metric label="MONTHLY AVG" value={currency(data.monthlyAverage)} /></View><View style={styles.half}><Metric label="RECURRING" value={currency(data.recurringMonthlyCommitment)} note="per month" /></View></View>
    <Text style={styles.section}>Top categories</Text><Card>{data.categoryBreakdown.slice(0, 5).map((item, index) => <View key={`${item.category}-${index}`} style={styles.row}><View style={styles.rowName}><View style={[styles.dot, { backgroundColor: item.color }]} /><Text style={styles.rowText}>{item.category}</Text></View><Text style={styles.amount}>{currency(item.amount)}</Text></View>)}</Card>
    <Text style={styles.section}>Upcoming commitments</Text><Card>{data.upcomingExpenses.length ? data.upcomingExpenses.slice(0, 5).map(item => <View key={item.id} style={styles.item}><View style={styles.flex}><Text style={styles.itemTitle}>{item.vendor || item.description}</Text><Text style={styles.note}>{shortDate(item.dueDate)}</Text></View><Text style={styles.amount}>{currency(item.amount)}</Text></View>) : <Text style={styles.note}>No commitments due in the next 30 days.</Text>}</Card>
  </>}</Screen>
}
function EmployeeHome() {
  const { user } = useAuth(); const remote = useRemote<PeopleSummary>('/employees/summary'); const data = remote.data
  return <Screen refreshing={remote.loading} onRefresh={remote.refresh}><PageTitle title={`Hello, ${user?.name || 'there'}`} subtitle="Your private Teinco-X employee workspace." /><State loading={remote.loading && !data} error={remote.error} />{data && <><View style={styles.metricGrid}><View style={styles.half}><Metric label="PENDING LEAVE" value={String(data.pendingLeave)} /></View><View style={styles.half}><Metric label="ON LEAVE" value={data.onLeaveCount ? 'Yes' : 'No'} /></View></View><Text style={styles.section}>Today’s attendance</Text><Card>{data.attendanceToday.length ? data.attendanceToday.map(item => <View style={styles.row} key={item.status}><Text style={styles.rowText}>{item.status.replace(/_/g, ' ')}</Text><Text style={styles.amount}>{item.count}</Text></View>) : <Text style={styles.note}>No attendance entry has been recorded today.</Text>}</Card><Card><Text style={styles.itemTitle}>Privacy protected</Text><Text style={styles.note}>Compensation access is {data.privacy.compensationAccess}. Your login only exposes employee-scoped information.</Text></Card></>}</Screen>
}
export function HomeScreen() { return useAuth().user?.role === 'admin' ? <AdminHome /> : <EmployeeHome /> }
const styles = StyleSheet.create({ metricGrid: { flexDirection: 'row', gap: 12 }, half: { flex: 1 }, metricLabel: { color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: .5 }, metricValue: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 8 }, note: { color: colors.muted, fontSize: 12, marginTop: 4, lineHeight: 18 }, section: { color: colors.ink, fontSize: 17, fontWeight: '800', marginTop: 8 }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 42, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, rowName: { flexDirection: 'row', alignItems: 'center', flex: 1 }, dot: { width: 9, height: 9, borderRadius: 5, marginRight: 9 }, rowText: { color: colors.ink, textTransform: 'capitalize' }, amount: { color: colors.ink, fontWeight: '700' }, item: { flexDirection: 'row', alignItems: 'center', paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, flex: { flex: 1 }, itemTitle: { color: colors.ink, fontWeight: '700' } })
