import { StyleSheet, Text, View } from 'react-native'
import { Card, PageTitle, Screen, State } from '../components/Ui'
import { useRemote } from '../hooks/useRemote'
import { colors, currency, shortDate } from '../theme'
type Subscription = { id: number; productName: string; subscriptionId: string; cost: number | string; currency: string; billingCycle: string; nextBillingDate?: string; autoRenewal: boolean; vendor?: { name: string }; category?: { name: string; color: string } }
export function SubscriptionsScreen() {
  const remote = useRemote<Subscription[]>('/subscriptions?status=active'); const data = remote.data
  return <Screen refreshing={remote.loading} onRefresh={remote.refresh}><PageTitle title="Subscriptions" subtitle={data ? `${data.length} active recurring services` : 'Recurring workspace commitments.'} /><State loading={remote.loading && !data} error={remote.error} />{data?.map(item => <Card key={item.id}><View style={styles.top}><View style={styles.flex}><Text style={styles.title}>{item.productName}</Text><Text style={styles.vendor}>{item.vendor?.name || item.subscriptionId}</Text></View><View style={styles.right}><Text style={styles.amount}>{currency(Number(item.cost), item.currency)}</Text><Text style={styles.cycle}>/{item.billingCycle.replace('_', ' ')}</Text></View></View><View style={styles.footer}><Text style={styles.due}>Next: {shortDate(item.nextBillingDate)}</Text><View style={[styles.badge, { backgroundColor: item.autoRenewal ? '#ECFDF5' : '#F3F4F6' }]}><Text style={[styles.badgeText, { color: item.autoRenewal ? colors.success : colors.muted }]}>{item.autoRenewal ? 'Auto-renew' : 'Manual'}</Text></View></View></Card>)}{data && !data.length && <Card><Text style={styles.empty}>No active subscriptions.</Text></Card>}</Screen>
}
const styles = StyleSheet.create({ top: { flexDirection: 'row', alignItems: 'flex-start' }, flex: { flex: 1 }, title: { color: colors.ink, fontSize: 16, fontWeight: '800' }, vendor: { color: colors.muted, fontSize: 12, marginTop: 5 }, right: { alignItems: 'flex-end' }, amount: { color: colors.ink, fontSize: 16, fontWeight: '800' }, cycle: { color: colors.muted, fontSize: 11, marginTop: 2, textTransform: 'capitalize' }, footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 16, paddingTop: 13, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border }, due: { color: colors.muted, fontSize: 12 }, badge: { borderRadius: 20, paddingHorizontal: 9, paddingVertical: 5 }, badgeText: { fontSize: 11, fontWeight: '800' }, empty: { color: colors.muted, textAlign: 'center' } })
