import { Link } from 'react-router-dom'
import { useApi, formatCurrency, formatDate } from '../hooks/useApi'

type Evidence = { label: string; href: string; date: string; amount: number }
type Signal = { id: string; title: string; severity: string; explanation: string; method: string; action: string; evidence: Evidence[]; evidenceCount: number }
type Intelligence = { generatedAt: string; windowStart: string; recordsReviewed: number; historyCount: number; anomalyCheck: string; signals: Signal[]; upcoming: Evidence[]; upcomingTotal: number }
function Records({ rows }: { rows: Evidence[] }) {
  return <ul className="mt-3 divide-y divide-slate-100 dark:divide-gray-700">{rows.map((row, index) => <li key={`${row.href}-${index}`} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><Link to={row.href} className="min-w-0 break-words text-blue-700 underline underline-offset-2 dark:text-blue-300">{row.label}</Link><span className="text-slate-600 dark:text-slate-300">{formatDate(row.date)} · {formatCurrency(row.amount)}</span></li>)}</ul>
}
export default function FlowIntelligence() {
  const { data, loading, error, refetch } = useApi<Intelligence>('/flow/intelligence')
  if (loading) return <p role="status" className="p-6">Checking workspace records…</p>
  if (error || !data) return <div role="alert" className="p-6 text-red-700 dark:text-red-300">Could not load checks. <button onClick={() => void refetch()} className="underline">Retry</button></div>
  return <section className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-xl font-semibold text-slate-900 dark:text-white">Evidence-based checks</h3><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Read-only checks · based on workspace records</p></div><button onClick={() => void refetch()} className="rounded-lg border px-3 py-2 text-sm dark:border-gray-600">Refresh checks</button></div>
    <p className="text-xs text-slate-500 dark:text-slate-400">Reviewed {data.recordsReviewed} active expenses from {formatDate(data.windowStart)} to {formatDate(data.generatedAt)}. Amounts are recorded INR values.</p>
    {data.anomalyCheck === 'insufficient_history' && <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">Large-expense checks need at least 10 positive expenses in the historical 60-day baseline. Currently available: {data.historyCount}. No anomaly conclusion is drawn from insufficient history.</div>}
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_320px]">
      <div className="space-y-4">{data.signals.map(signal => <article key={signal.id} className="rounded-xl border border-slate-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><p className="text-xs font-semibold uppercase tracking-wide text-amber-700 dark:text-amber-300">Review suggested</p><h4 className="mt-2 font-semibold text-slate-900 dark:text-white">{signal.title}</h4><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{signal.explanation}</p><p className="mt-3 text-sm font-medium">{signal.action}</p><details className="mt-4"><summary className="cursor-pointer text-sm text-blue-700 dark:text-blue-300">Method and supporting records ({signal.evidenceCount})</summary><p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">{signal.method}</p><Records rows={signal.evidence} />{signal.evidenceCount > signal.evidence.length && <p className="text-xs text-slate-500 dark:text-slate-400">Showing {signal.evidence.length} of {signal.evidenceCount} matching records.</p>}</details></article>)}{!data.signals.length && <div className="rounded-xl border border-slate-200 bg-white p-6 dark:border-gray-700 dark:bg-gray-800"><h4 className="font-semibold">No review signals from the available checks</h4><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">This is not a guarantee that the records are error-free. Coverage is limited to the rules and time window shown above.</p></div>}</div>
      <aside className="rounded-xl border border-slate-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><h4 className="font-semibold">Upcoming ledger payments</h4><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Next 30 days · recurring expense due dates</p><p className="finance-value mt-4 text-2xl font-semibold">{formatCurrency(data.upcomingTotal)}</p><Records rows={data.upcoming} />{!data.upcoming.length && <p className="mt-4 text-sm text-slate-500 dark:text-slate-400">No recurring ledger payments are scheduled. Subscription renewals are managed separately.</p>}</aside>
    </div>
  </section>
}
