import { useMemo, useRef, useState, type DragEvent, type FormEvent, type ReactNode } from 'react'
import { FolderKanban, Plus, X, MessageSquare, Pencil, Trash2 } from 'lucide-react'
import { apiDelete, apiPost, apiPut, formatDate, useApi } from '../hooks/useApi'
import { useRole } from '../context/RoleContext'

type Project = { id: number; code: string; name: string; description?: string; logoDataUrl?: string; status: string; color: string; budget: number; _count?: { workItems: number } }
type Employee = { id: number; name: string }
type Comment = { id: number; body: string; createdAt: string; author: { name?: string; email: string } }
type Issue = { id: number; key: string; projectId: number; type: string; summary: string; description?: string; status: string; priority: string; assigneeId?: number; assignee?: Employee; sprint?: string; storyPoints?: number; dueDate?: string; labels?: string; comments: Comment[] }
const columns = [['backlog', 'Backlog'], ['todo', 'To do'], ['in_progress', 'In progress'], ['review', 'Review'], ['blocked', 'Blocked'], ['done', 'Done']] as const
const initialIssue = { type: 'task', summary: '', description: '', status: 'backlog', priority: 'medium', assigneeId: '', sprint: '', storyPoints: '', dueDate: '', labels: '' }

export default function ProjectManagement() {
  const { isAdmin } = useRole()
  const projectsRemote = useApi<Project[]>('/projects'), employeesRemote = useApi<Employee[]>('/employees')
  const [projectId, setProjectId] = useState<number | null>(null)
  const selectedProject = projectId || projectsRemote.data?.[0]?.id || null
  const issuesRemote = useApi<Issue[]>(selectedProject ? `/projects/issues?projectId=${selectedProject}` : null)
  const [showProject, setShowProject] = useState(false), [editingProject, setEditingProject] = useState<Project | null>(null), [showIssue, setShowIssue] = useState(false), [editingIssue, setEditingIssue] = useState<Issue | null>(null), [selected, setSelected] = useState<Issue | null>(null)
  const [projectForm, setProjectForm] = useState({ name: '', code: '', description: '', logoDataUrl: '', status: 'active', budget: '', color: '#6366f1' })
  const [issueForm, setIssueForm] = useState(initialIssue), [comment, setComment] = useState(''), [error, setError] = useState(''), [saving, setSaving] = useState(false)
  const issues = issuesRemote.data || []
  const metrics = useMemo(() => ({ open: issues.filter(i => i.status !== 'done').length, blocked: issues.filter(i => i.status === 'blocked').length, overdue: issues.filter(i => i.status !== 'done' && i.dueDate && new Date(i.dueDate) < new Date()).length, points: issues.filter(i => i.status === 'done').reduce((sum, i) => sum + (i.storyPoints || 0), 0) }), [issues])
  const createProject = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const row = await apiPost('/projects', { ...projectForm, logoDataUrl: projectForm.logoDataUrl || null, budget: Number(projectForm.budget) || 0, code: projectForm.code || undefined }); await projectsRemote.refetch(); setProjectId(row.id); setShowProject(false) } catch (e) { setError(e instanceof Error ? e.message : 'Could not create project') } finally { setSaving(false) } }
  const openProjectEditor = (project: Project) => { setProjectForm({ name: project.name, code: project.code, description: project.description || '', logoDataUrl: project.logoDataUrl || '', status: project.status, budget: String(project.budget || ''), color: project.color }); setEditingProject(project) }
  const chooseLogo = (file?: File) => { if (!file) return; if (!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size > 1_000_000) { setError('Choose a PNG, JPEG, or WebP logo smaller than 1 MB.'); return } const reader = new FileReader(); reader.onload = () => setProjectForm(form => ({ ...form, logoDataUrl: String(reader.result) })); reader.readAsDataURL(file) }
  const updateProject = async (event: FormEvent) => { event.preventDefault(); if (!editingProject) return; setSaving(true); setError(''); try { await apiPut(`/projects/${editingProject.id}`, { ...projectForm, logoDataUrl: projectForm.logoDataUrl || null, budget: Number(projectForm.budget) || 0 }); await projectsRemote.refetch(); setEditingProject(null) } catch (e) { setError(e instanceof Error ? e.message : 'Could not update project') } finally { setSaving(false) } }
  const deleteProject = async (project: Project) => { if (!window.confirm(`Delete ${project.name}? Its work items will be deleted. Linked expenses, budgets, and schedule records will be kept without a project link.`)) return; setSaving(true); setError(''); try { await apiDelete(`/projects/${project.id}`); const remaining = (projectsRemote.data || []).filter(row => row.id !== project.id); setProjectId(remaining[0]?.id || null); setEditingProject(null); await projectsRemote.refetch() } catch (e) { setError(e instanceof Error ? e.message : 'Could not delete project') } finally { setSaving(false) } }
  const openIssueEditor = (issue: Issue) => { setIssueForm({ type: issue.type, summary: issue.summary, description: issue.description || '', status: issue.status, priority: issue.priority, assigneeId: issue.assigneeId ? String(issue.assigneeId) : '', sprint: issue.sprint || '', storyPoints: issue.storyPoints == null ? '' : String(issue.storyPoints), dueDate: issue.dueDate ? issue.dueDate.slice(0, 10) : '', labels: issue.labels || '' }); setEditingIssue(issue); setSelected(null); setShowIssue(true) }
  const createIssue = async (event: FormEvent) => { event.preventDefault(); if (!selectedProject) return; const points = issueForm.storyPoints === '' ? null : Number(issueForm.storyPoints); if (issueForm.summary.trim().length < 2) { setError('Enter a work-item summary with at least 2 characters.'); return } if (points !== null && (!Number.isInteger(points) || points < 0 || points > 100)) { setError('Story points must be a whole number from 0 to 100.'); return } setSaving(true); setError(''); try { const payload = { projectId: Number(selectedProject), type: issueForm.type, summary: issueForm.summary.trim(), description: issueForm.description.trim() || null, status: issueForm.status, priority: issueForm.priority, assigneeId: issueForm.assigneeId ? Number(issueForm.assigneeId) : null, sprint: issueForm.sprint.trim() || null, storyPoints: points, dueDate: issueForm.dueDate || null, labels: issueForm.labels.trim() || null }; if (editingIssue) await apiPut(`/projects/issues/${editingIssue.id}`, payload); else await apiPost('/projects/issues', payload); setIssueForm(initialIssue); setEditingIssue(null); setShowIssue(false); await issuesRemote.refetch(); await projectsRemote.refetch() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save work item') } finally { setSaving(false) } }
  const move = async (issue: Issue, status: string) => { if (issue.status === status) return; await apiPut(`/projects/issues/${issue.id}`, { status }); await issuesRemote.refetch() }
  const addComment = async () => { if (!selected || !comment.trim()) return; await apiPost(`/projects/issues/${selected.id}/comments`, { body: comment }); setComment(''); await issuesRemote.refetch(); const rows = await fetch(`/api/projects/issues?projectId=${selected.projectId}`, { headers: { Authorization: `Bearer ${localStorage.getItem('teinco-x-token') || ''}` } }).then(r => r.json()); setSelected(rows.find((row: Issue) => row.id === selected.id) || null) }
  return <div className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="brand-heading">Projects & Taskboard</h2><p className="brand-caption mt-1">{isAdmin ? 'Plan delivery, assign work, track sprints, and resolve blockers.' : 'View shared work items and comment on the tasks you are following.'}</p></div>{isAdmin && <div className="flex gap-2"><button onClick={() => setShowProject(true)} className="rounded-lg border bg-white px-3 py-2 text-sm dark:bg-gray-800"><Plus className="mr-1 inline h-4 w-4" />Project</button><button disabled={!selectedProject} onClick={() => setShowIssue(true)} className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-50"><Plus className="mr-1 inline h-4 w-4" />Work item</button></div>}</header>
    <div className="flex gap-3 overflow-x-auto pb-1">{projectsRemote.data?.map(project => <div key={project.id} className={`min-w-56 rounded-xl border p-4 ${selectedProject === project.id ? 'border-blue-500 bg-blue-50 dark:bg-blue-950/30' : 'bg-white dark:bg-gray-800'}`}><button onClick={() => setProjectId(project.id)} className="w-full text-left"><div className="flex items-center gap-2">{project.logoDataUrl ? <img src={project.logoDataUrl} alt="" className="h-10 w-10 rounded-lg object-cover"/> : <span className="h-3 w-3 rounded" style={{ background: project.color }} />}<strong>{project.name}</strong></div><p className="mt-2 text-xs text-slate-500">{project.code} · {project._count?.workItems || 0} items</p></button>{isAdmin && <div className="mt-3 flex gap-2 border-t pt-3 dark:border-gray-700"><button onClick={() => openProjectEditor(project)} className="rounded-md px-2 py-1 text-xs text-blue-700 hover:bg-blue-100"><Pencil className="mr-1 inline h-3.5 w-3.5"/>Edit</button><button onClick={() => void deleteProject(project)} disabled={saving} className="rounded-md px-2 py-1 text-xs text-red-600 hover:bg-red-50"><Trash2 className="mr-1 inline h-3.5 w-3.5"/>Delete</button></div>}</div>)}</div>
    {!projectsRemote.loading && !projectsRemote.data?.length && <div className="brand-card p-10 text-center"><FolderKanban className="mx-auto h-10 w-10 text-blue-500"/><h3 className="mt-3 font-semibold">Create your first project</h3><p className="mt-1 text-sm text-slate-500">Projects hold the shared backlog and delivery board.</p></div>}
    {!!selectedProject && <><div className="grid gap-3 sm:grid-cols-4">{[['Open', metrics.open, 'text-blue-700'], ['Blocked', metrics.blocked, 'text-red-700'], ['Overdue', metrics.overdue, 'text-amber-700'], ['Points done', metrics.points, 'text-emerald-700']].map(([label, value, color]) => <div key={String(label)} className="brand-card p-4"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 text-2xl font-semibold ${color}`}>{value}</p></div>)}</div>
    <div className="flex gap-4 overflow-x-auto pb-4">{columns.map(([status, label]) => <section key={status} onDragOver={isAdmin ? e => e.preventDefault() : undefined} onDrop={isAdmin ? e => { const issue = issues.find(row => row.id === Number(e.dataTransfer.getData('text/plain'))); if (issue) void move(issue, status) } : undefined} className="w-72 shrink-0 rounded-xl bg-slate-100 p-3 dark:bg-gray-900"><div className="mb-3 flex justify-between"><h3 className="text-sm font-semibold">{label}</h3><span className="rounded-full bg-white px-2 text-xs dark:bg-gray-800">{issues.filter(i => i.status === status).length}</span></div><div className="space-y-3">{issues.filter(i => i.status === status).map(issue => <button draggable={isAdmin} onDragStart={isAdmin ? (e: DragEvent) => e.dataTransfer.setData('text/plain', String(issue.id)) : undefined} onClick={() => setSelected(issue)} key={issue.id} className="w-full rounded-lg border bg-white p-3 text-left shadow-sm dark:border-gray-700 dark:bg-gray-800"><div className="flex justify-between gap-2"><span className="text-xs font-semibold text-blue-700">{issue.key}</span><span className={`text-[10px] font-semibold uppercase ${issue.priority.includes('high') ? 'text-red-600' : 'text-slate-500'}`}>{issue.priority}</span></div><p className="mt-2 text-sm font-medium">{issue.summary}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-slate-500">{issue.assignee && <span>{issue.assignee.name}</span>}{issue.sprint && <span>· {issue.sprint}</span>}{issue.storyPoints != null && <span>· {issue.storyPoints} pts</span>}{issue.dueDate && <span className={new Date(issue.dueDate) < new Date() && issue.status !== 'done' ? 'text-red-600' : ''}>· {formatDate(issue.dueDate)}</span>}</div></button>)}</div></section>)}</div></>}
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {showProject && <Modal title="Create project" close={() => setShowProject(false)}><form onSubmit={createProject} className="space-y-3"><LogoField value={projectForm.logoDataUrl} choose={chooseLogo} clear={() => setProjectForm(f=>({...f,logoDataUrl:''}))}/><Field label="Project name" value={projectForm.name} set={value => setProjectForm(f => ({...f,name:value}))} required/><Field label="Key (optional)" value={projectForm.code} set={value => setProjectForm(f => ({...f,code:value.toUpperCase()}))}/><Field label="Description" value={projectForm.description} set={value => setProjectForm(f => ({...f,description:value}))}/><Field label="Budget" type="number" value={projectForm.budget} set={value => setProjectForm(f => ({...f,budget:value}))}/><button disabled={saving} className="w-full rounded-lg bg-blue-600 py-2 text-white">Create project</button></form></Modal>}
    {editingProject && <Modal title={`Edit ${editingProject.name}`} close={() => setEditingProject(null)}><form onSubmit={updateProject} className="space-y-3"><LogoField value={projectForm.logoDataUrl} choose={chooseLogo} clear={() => setProjectForm(f=>({...f,logoDataUrl:''}))}/><Field label="Project name" value={projectForm.name} set={value => setProjectForm(f => ({...f,name:value}))} required/><Field label="Project key" value={projectForm.code} set={value => setProjectForm(f => ({...f,code:value.toUpperCase()}))} required/><Field label="Description" value={projectForm.description} set={value => setProjectForm(f => ({...f,description:value}))}/><Select label="Status" value={projectForm.status} values={['active','paused','completed','archived']} set={value => setProjectForm(f => ({...f,status:value}))}/><Field label="Budget" type="number" value={projectForm.budget} set={value => setProjectForm(f => ({...f,budget:value}))}/><Field label="Colour" type="color" value={projectForm.color} set={value => setProjectForm(f => ({...f,color:value}))}/><button disabled={saving} className="w-full rounded-lg bg-blue-600 py-2 text-white">Save changes</button><button type="button" onClick={() => void deleteProject(editingProject)} disabled={saving} className="w-full rounded-lg border border-red-200 py-2 text-red-600">Delete project</button></form></Modal>}
    {showIssue && <Modal title="Create work item" close={() => setShowIssue(false)}><form onSubmit={createIssue} className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2 text-sm">Summary<input required value={issueForm.summary} onChange={e => setIssueForm(f => ({...f,summary:e.target.value}))} className="mt-1 w-full rounded-lg border p-2 dark:bg-gray-900"/></label><Select label="Type" value={issueForm.type} values={['epic','story','task','bug']} set={v => setIssueForm(f=>({...f,type:v}))}/><Select label="Priority" value={issueForm.priority} values={['lowest','low','medium','high','highest']} set={v => setIssueForm(f=>({...f,priority:v}))}/><Select label="Status" value={issueForm.status} values={columns.map(c=>c[0])} set={v => setIssueForm(f=>({...f,status:v}))}/><label className="text-sm">Assignee<select value={issueForm.assigneeId} onChange={e=>setIssueForm(f=>({...f,assigneeId:e.target.value}))} className="mt-1 w-full rounded-lg border p-2 dark:bg-gray-900"><option value="">Unassigned</option>{employeesRemote.data?.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><Field label="Sprint" value={issueForm.sprint} set={v=>setIssueForm(f=>({...f,sprint:v}))}/><Field label="Story points" type="number" value={issueForm.storyPoints} set={v=>setIssueForm(f=>({...f,storyPoints:v}))}/><Field label="Due date" type="date" value={issueForm.dueDate} set={v=>setIssueForm(f=>({...f,dueDate:v}))}/><Field label="Labels" value={issueForm.labels} set={v=>setIssueForm(f=>({...f,labels:v}))}/><DescriptionEditor value={issueForm.description} onChange={value => setIssueForm(f => ({ ...f, description: value }))}/><button disabled={saving} className="sm:col-span-2 rounded-lg bg-blue-600 py-2 text-white">Create work item</button></form></Modal>}
    {selected && <Modal title={`${selected.key} · ${selected.summary}`} close={() => setSelected(null)}><div className="space-y-4"><RichDescription value={selected.description}/><div className="grid grid-cols-2 gap-2 text-sm"><p><strong>Status:</strong> {selected.status.replace('_',' ')}</p><p><strong>Priority:</strong> {selected.priority}</p><p><strong>Assignee:</strong> {selected.assignee?.name || 'Unassigned'}</p><p><strong>Sprint:</strong> {selected.sprint || 'Backlog'}</p></div><div><h4 className="font-semibold"><MessageSquare className="mr-1 inline h-4 w-4"/>Comments</h4>{selected.comments?.map(c=><div key={c.id} className="mt-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-gray-900"><p>{c.body}</p><p className="mt-1 text-xs text-slate-500">{c.author.name || c.author.email} · {formatDate(c.createdAt)}</p></div>)}<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment" className="mt-3 w-full rounded-lg border p-2 dark:bg-gray-900"/><button onClick={() => void addComment()} className="mt-2 rounded-lg bg-blue-600 px-3 py-2 text-sm text-white">Comment</button></div>{isAdmin && <button onClick={async()=>{await apiDelete(`/projects/issues/${selected.id}`);setSelected(null);void issuesRemote.refetch()}} className="text-sm text-red-600">Delete work item</button>}</div></Modal>}
    {selected && isAdmin && <button type="button" onClick={() => openIssueEditor(selected)} className="fixed bottom-6 right-6 z-[60] rounded-full bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-lg">Edit</button>}
  </div>
}
function DescriptionEditor({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const ref = useRef<HTMLTextAreaElement>(null)
  const wrap = (before: string, after = before) => {
    const input = ref.current, start = input?.selectionStart ?? value.length, end = input?.selectionEnd ?? value.length
    const next = `${value.slice(0, start)}${before}${value.slice(start, end) || 'text'}${after}${value.slice(end)}`
    onChange(next)
    requestAnimationFrame(() => { input?.focus(); input?.setSelectionRange(start + before.length, end + before.length + (start === end ? 4 : 0)) })
  }
  const bullets = () => { const input = ref.current, start = input?.selectionStart ?? value.length, end = input?.selectionEnd ?? value.length, selected = value.slice(start, end) || 'List item'; onChange(`${value.slice(0, start)}${selected.split('\n').map(line => `• ${line}`).join('\n')}${value.slice(end)}`); requestAnimationFrame(() => input?.focus()) }
  return <label className="sm:col-span-2 text-sm">Description<div className="mt-1 flex gap-1 rounded-t-lg border border-b-0 bg-slate-50 p-1 dark:border-gray-700 dark:bg-gray-900"><button type="button" onClick={() => wrap('**')} className="rounded px-2 py-1 font-bold hover:bg-white dark:hover:bg-gray-800" title="Bold">B</button><button type="button" onClick={() => wrap('__')} className="rounded px-2 py-1 underline hover:bg-white dark:hover:bg-gray-800" title="Underline">U</button><button type="button" onClick={bullets} className="rounded px-2 py-1 hover:bg-white dark:hover:bg-gray-800" title="Bullet points">• List</button></div><textarea ref={ref} value={value} onChange={e => onChange(e.target.value)} placeholder="Use the toolbar to format important details." className="min-h-28 w-full rounded-b-lg border p-2 dark:border-gray-700 dark:bg-gray-900"/></label>
}
function RichDescription({ value }: { value?: string }) {
  if (!value) return <p className="text-sm text-slate-500">No description.</p>
  const inline = (text: string) => text.split(/(\*\*[^*]+\*\*|__[^_]+__)/g).map((part, index) => part.startsWith('**') ? <strong key={index}>{part.slice(2, -2)}</strong> : part.startsWith('__') ? <u key={index}>{part.slice(2, -2)}</u> : part)
  return <div className="space-y-1 text-sm text-slate-700 dark:text-slate-200">{value.split('\n').map((line, index) => line.startsWith('• ') || line.startsWith('- ') ? <div key={index} className="flex gap-2"><span>•</span><span>{inline(line.slice(2))}</span></div> : <p key={index}>{inline(line)}</p>)}</div>
}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-xl dark:bg-gray-800"><div className="mb-4 flex justify-between"><h3 className="text-lg font-semibold">{title}</h3><button onClick={close}><X className="h-5 w-5"/></button></div>{children}</div></div> }
function Field({label,value,set,type='text',required=false}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean}) { return <label className="text-sm">{label}<input type={type} required={required} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border p-2 dark:bg-gray-900"/></label> }
function Select({label,value,values,set}:{label:string;value:string;values:readonly string[];set:(v:string)=>void}) { return <label className="text-sm">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border p-2 capitalize dark:bg-gray-900">{values.map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></label> }
function LogoField({value,choose,clear}:{value:string;choose:(file?:File)=>void;clear:()=>void}) { return <label className="block text-sm">Project logo<div className="mt-2 flex items-center gap-3">{value ? <img src={value} alt="Project logo preview" className="h-16 w-16 rounded-xl border object-cover"/> : <div className="grid h-16 w-16 place-items-center rounded-xl border bg-slate-50"><FolderKanban className="h-7 w-7 text-slate-400"/></div>}<div><input type="file" accept="image/png,image/jpeg,image/webp" onChange={event=>choose(event.target.files?.[0])} className="block max-w-full text-xs"/><p className="mt-1 text-xs text-slate-500">PNG, JPEG or WebP · maximum 1 MB</p>{value && <button type="button" onClick={clear} className="mt-1 text-xs text-red-600">Remove logo</button>}</div></div></label> }
