import { ArrowRight, Bot, BrainCircuit, CheckCircle2, MapPin, Menu, ShieldCheck, Sparkles, Workflow, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'

const capabilities = [
  { icon: BrainCircuit, title: 'AIML software', copy: 'Custom AI software, smart dashboards, retrieval systems, and products designed around real business problems.', color: 'from-blue-500 to-indigo-600' },
  { icon: Workflow, title: 'Automation systems', copy: 'Connected workflows that bring people, data, content, and decisions together with less manual effort.', color: 'from-fuchsia-500 to-violet-600' },
  { icon: Bot, title: 'Conversational AI', copy: 'Natural voice and chat experiences that listen, respond, and help people work with complex information.', color: 'from-cyan-500 to-blue-600' },
]
const values = ['Product-agnostic', 'Human-first', 'Real-world utility', 'Built to scale']

export default function PublicHome() {
  const [open, setOpen] = useState(false)
  return <div className="min-h-screen overflow-hidden bg-[#071127] text-white">
    <div className="absolute inset-x-0 top-0 h-[760px] bg-[radial-gradient(circle_at_18%_15%,rgba(49,92,243,.5),transparent_32%),radial-gradient(circle_at_80%_8%,rgba(217,70,239,.3),transparent_28%),radial-gradient(circle_at_70%_62%,rgba(6,182,212,.22),transparent_30%)]" />
    <nav className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
      <Link to="/" className="flex items-center gap-3"><img src="/teinco-logo.png" alt="Teinco-X" className="h-11 w-auto rounded-lg bg-white object-contain p-1"/><div><strong className="block font-heading tracking-wide">TEINCO-X</strong><span className="text-[10px] uppercase tracking-[.22em] text-blue-200">Technology · Innovation · Communication</span></div></Link>
      <button className="rounded-xl border border-white/15 p-2 md:hidden" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button>
      <div className={`${open?'flex':'hidden'} absolute left-5 right-5 top-20 flex-col gap-4 rounded-2xl border border-white/10 bg-[#101b35] p-5 shadow-2xl md:static md:flex md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0 md:shadow-none`}><a href="#about" className="text-sm text-slate-200 hover:text-white">About</a><a href="#solutions" className="text-sm text-slate-200 hover:text-white">What we do</a><a href="#approach" className="text-sm text-slate-200 hover:text-white">Approach</a><a href="#contact" className="text-sm text-slate-200 hover:text-white">Contact</a><Link to="/login" className="rounded-xl bg-white px-4 py-2.5 text-center text-sm font-semibold text-[#162450]">Open workspace</Link></div>
    </nav>
    <main className="relative">
      <section className="mx-auto grid min-h-[650px] max-w-7xl items-center gap-14 px-5 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pt-24">
        <div><div className="inline-flex items-center gap-2 rounded-full border border-blue-300/20 bg-blue-400/10 px-4 py-2 text-xs font-semibold uppercase tracking-[.18em] text-blue-200"><Sparkles className="h-4 w-4"/>The AI operating layer</div><h1 className="mt-7 max-w-3xl font-heading text-5xl font-semibold leading-[1.06] sm:text-6xl lg:text-7xl">Intelligence that becomes <span className="bg-gradient-to-r from-[#79a5ff] via-[#b493ff] to-[#55e1dc] bg-clip-text text-transparent">real-world execution.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Teinco-X builds the AI layer on top of products, data, and operations—turning complex workflows into useful software, clear decisions, and natural conversations.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/login" className="inline-flex items-center gap-2 rounded-xl bg-[#4770ff] px-6 py-3.5 font-semibold shadow-[0_16px_35px_rgba(71,112,255,.35)] transition hover:-translate-y-0.5">Enter Teinco-X Workspace <ArrowRight className="h-4 w-4"/></Link><a href="#about" className="rounded-xl border border-white/15 bg-white/5 px-6 py-3.5 font-semibold hover:bg-white/10">Explore the company</a></div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-6 rounded-[3rem] bg-gradient-to-br from-blue-500/30 via-purple-500/20 to-cyan-400/20 blur-2xl"/><div className="relative rounded-[2rem] border border-white/15 bg-white/[.08] p-5 shadow-2xl backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-xs uppercase tracking-[.2em] text-blue-200">Teinco-X Workspace</p><p className="mt-1 font-heading text-xl">Business intelligence, connected</p></div><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-500"><Bot/></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><MiniCard label="Vyom AI" value="Conversational insight" tint="bg-blue-500/20 text-blue-200"/><MiniCard label="Flow" value="Operational intelligence" tint="bg-purple-500/20 text-purple-200"/><MiniCard label="Projects" value="Delivery visibility" tint="bg-cyan-500/20 text-cyan-200"/><MiniCard label="Ledger" value="Financial clarity" tint="bg-emerald-500/20 text-emerald-200"/></div><div className="mt-4 rounded-2xl border border-white/10 bg-[#0b1732]/80 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-purple-500"><Sparkles className="h-5 w-5"/></span><div><p className="text-sm font-semibold">What needs attention today?</p><p className="text-xs text-slate-400">Vyom uses verified workspace facts.</p></div></div><div className="mt-5 flex h-24 items-end gap-2">{[38,58,44,76,63,88,72,96,84,100].map((height,index)=><span key={index} className="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-cyan-300" style={{height:`${height}%`}}/>)}</div></div></div></div>
      </section>
      <section id="about" className="bg-white px-5 py-24 text-[#101828] lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-600">About Teinco-X</p><div className="mt-4 grid gap-10 lg:grid-cols-2"><h2 className="font-heading text-4xl font-semibold leading-tight sm:text-5xl">An AI and automation company built for practical execution.</h2><div><p className="text-lg leading-8 text-slate-600">Our work sits at the intersection of AI engineering, machine-learning workflows, product development, and automation. We help organizations reduce manual work, improve decisions, and create digital experiences that can think, respond, and scale.</p><div className="mt-7 grid grid-cols-2 gap-3">{values.map(value=><div key={value} className="flex items-center gap-2 rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-950"><CheckCircle2 className="h-4 w-4 text-blue-600"/>{value}</div>)}</div></div></div></div></section>
      <section id="solutions" className="bg-[#f4f7ff] px-5 py-24 text-[#101828] lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-violet-600">What we build</p><h2 className="mt-4 font-heading text-4xl font-semibold">Technology, innovation, and communication in one operating rhythm.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{capabilities.map(item=><article key={item.title} className="rounded-[1.5rem] border border-white bg-white p-7 shadow-[0_18px_50px_rgba(30,58,138,.09)]"><div className={`grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br ${item.color} text-white`}><item.icon/></div><h3 className="mt-6 text-xl font-semibold">{item.title}</h3><p className="mt-3 leading-7 text-slate-600">{item.copy}</p></article>)}</div></div></section>
      <section id="approach" className="bg-white px-5 py-24 text-[#101828] lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-600">Our approach</p><h2 className="mt-4 font-heading text-4xl font-semibold">A clear path from idea to governed product.</h2><p className="mt-5 leading-7 text-slate-600">We combine engineering, integration, experience design, and human oversight so intelligence remains useful and dependable.</p></div><div className="grid gap-4 sm:grid-cols-2">{[['01','Discover','Map the product, data, users, and outcomes.'],['02','Build the layer','Engineer models, retrieval, and automation.'],['03','Integrate','Connect systems and design the experience.'],['04','Govern & scale','Add guardrails, oversight, and a reusable core.']].map(([n,title,copy])=><div key={n} className="rounded-2xl border border-slate-200 p-6"><span className="text-sm font-bold text-blue-600">{n}</span><h3 className="mt-3 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{copy}</p></div>)}</div></div></div></section>
      <section id="contact" className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#152b69] to-[#27145c] p-8 sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-200">Build with Teinco-X</p><h2 className="mt-4 font-heading text-4xl font-semibold">Bring an intelligent layer to your product.</h2><p className="mt-4 max-w-2xl text-slate-300">For AI software, automation, conversational experiences, or enterprise integration, connect with our Bengaluru team.</p><p className="mt-5 flex items-center gap-2 text-sm text-slate-300"><MapPin className="h-4 w-4"/>Lavelle Road, Bengaluru, Karnataka</p></div><div className="flex flex-col gap-3"><a href="mailto:info@teinco-x.com" className="rounded-xl bg-white px-6 py-3 text-center font-semibold text-[#172554]">info@teinco-x.com</a><Link to="/login" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 px-6 py-3 font-semibold">Workspace sign in <ShieldCheck className="h-4 w-4"/></Link></div></div></section>
    </main>
    <footer className="border-t border-white/10 px-5 py-8 text-sm text-slate-400"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-3"><p>© 2026 Teinco-X. All rights reserved.</p><p>Technology · Innovation · Communication</p></div></footer>
  </div>
}
function MiniCard({label,value,tint}:{label:string;value:string;tint:string}) { return <div className="rounded-2xl border border-white/10 bg-white/[.06] p-4"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${tint}`}>{label}</span><p className="mt-3 text-sm font-semibold">{value}</p></div> }
